services:
  mssql:
    container_name: mrjb-hangfire-mssql
    hostname: mrjb-hangfire-mssql
    build: 
        context: ./docker/mssql/
        dockerfile: Dockerfile
    env_file:
      - .env
    image: ${DOCKER_REGISTRY}/mrjb-hangfire-mssql:dev
    ports:
      - 1434:1433
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'NyLct4D@7K{s'
    volumes:
     - ./data/:/var/opt/mssql/data